---
name: w1
description: Thank you for knowing me.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0-257.0.dev <4.0.0"
dependencies:
  antdesign_icons: ^0.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_circular_text: ^0.3.1
  google_fonts: ^4.0.3
  lottie: ^2.3.0
  url_launcher: ^6.1.10
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
